### ISSUE TITLE
As a test reporter, I need better summary information

### ISSUE THREAD

**Issue by tmcgee123** [tmcgee123/karma-spec-reporter#65]
- [ ] Print out all tests at once #46 
- [ ] Multiple browser reporting #49 
- [ ] Only show passed/error based on flag #60 

These are all items that have been requested as part of the Summarized Reporting, any help would be much appreciated!

**Comment by brandonros** [comment]
What about progress? Like, if I have 2,500 unit tests, I like knowing I'm at 1,200 / 2,500 3 minutes in, for example.

**Comment by whyboris** [comment]
There _are_ other reporters that may suit your needs, _and_ you can use more than one. 
For example @brandonros you could have `progress` reporter (comes with _Karma_), and this additional one.
I wrote a reporter that I think may suite some of your needs: [karma-helpful-reporter](https://github.com/whyboris/karma-helpful-reporter)

**Comment by Finesse** [comment]
You can use [karma-summary-reporter](https://www.npmjs.com/package/karma-summary-reporter) for clean, concise and informative summaries

**Comment by tmcgee123** [comment]
Going with @Finesse suggestion
